version: '3.8'

services:
  db:
    image: postgres:16 # Use a specific version for stability, e.g., postgres:16
    restart: always
    environment:
      POSTGRES_USER: appointmentUser
      POSTGRES_PASSWORD: appointmentpassword
      POSTGRES_DB: appointmentDatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: 128mb # Recommended for PostgreSQL performance in Docker

volumes:
  pgdata: